### ISSUE TITLE
Support for Android platform

### ISSUE THREAD

**Issue by Jobians** [mumumusuc/termux-flutter#14]
Please how to make this run on Android platform instead of Linux

**Comment by mumumusuc** [comment]
Do you mean use flutter to build apk and deploy it on Android device instead of running locally?

This project provides you a full flutter experience, yes, you can build a apk file by running `flutter build apk` with **termuxed** [android-sdk](https://github.com/Lzhiyong/termux-ndk), `flutter doctor -v` would tell you what needed.

**Comment by mumumusuc** [comment]
> No, I mean see my project preview in android platform not Linux

1. [How TO Connect ADB Devices](https://github.com/bdloser404/Fluttermux#how-to-connect-adb-devices)

2. `flutter devices` would list all devices connected.

3. `flutter run -d <your android device id>`

**Comment by mumumusuc** [comment]
README updated
